name: Build and Deploy to GitHub Pages

on: [push]
defaults:
  run:
    working-directory: frontend
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '21.7.1'
            - name: Install Dependencies
              run: npm i --legacy-peer-deps

            - name: Build react app
              run: REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} npm run build

            - name: Deploy 🚀
              uses: peaceiris/actions-gh-pages@v3
              with:
                publish_dir: ../build
